create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table "cl0ud"."person" ("id" bigint not null, "age" integer, "name" varchar(255), primary key ("id"));
create sequence "person_seq" start with 1 increment by 50;
create table cl0ud.person (id bigint not null, age integer, name varchar(255), primary key (id));
create sequence person_seq start with 1 increment by 50;
create table cl0ud.person (id bigint not null, age integer, name varchar(255), primary key (id));
create sequence person_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create sequence person_seq start with 1 increment by 50;
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create sequence person_seq start with 1 increment by 50;
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create sequence person_seq start with 1 increment by 50;
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create sequence person_seq start with 1 increment by 50;
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create sequence person_seq start with 1 increment by 50;
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create sequence person_seq start with 1 increment by 50;
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create sequence person_seq start with 1 increment by 50;
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
create sequence permission_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table permission (id bigint not null, description varchar(255), primary key (id));
create table person (id bigint not null, age integer, name varchar(255), primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
