version: '3.3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=cl0ud
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=terra
    volumes:
      - /var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - angelo-zero-network
  cl0ud:
    image: angelozero/cl0ud
    restart: always
    build: ./
    working_dir: /
    environment:
      SPRING.DATASOURCE.DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres:5432/cl0ud
      SPRING.DATASOURCE.USERNAME: master
      SPRING.DATASOURCE.PASSWORD: terra
    ports:
      - '8080:8080'
    command:
      - 'mvn spring-boot: run'
    depends_on:
      - postgres
    networks:
      - angelo-zero-network
networks:
  angelo-zero-network:
    driver: bridge
