# Spring Boot configuration
spring:
  output:
    ansi:
      enabled: ALWAYS

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cl0ud?currentSchema=cl0ud
    username: master
    password: terra
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
      dialect: org.hibernate.dialect.PostgreSQLDialect
      globally_quoted_identifiers: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
main:
  banner-mode=off:
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: info

# Server configuration
server:
  port: 8080 #set your port

# JWT
security:
  jwt:
    token:
      # // https://www.allkeysgenerator.com/ --> Encryption key --> 256-bit --> Hex ? yes (cheked)
      secret-key: 4D6251655468566D597133743677397A24432646294A404E635266556A586E5A
      milliseconds: 3600000
      hours: 10800000 # 3Hs